/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.HoaDonDAO;
import Model.HoaDonModel;
import Pojo.HoaDonPoJo;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Administrator
 */
public class HoaDonPane extends javax.swing.JPanel {

    HoaDonModel hoa_don_model;
    HoaDonDAO hoa_don_DAO;

    /**
     * Creates new form HoaDonPane
     */
    public HoaDonPane() {
        initComponents();
        hoa_don_DAO = new HoaDonDAO();

        try {
            initHoaDonTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(view.NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(view.NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        handleSelected();
    }

    public void initHoaDonTable() throws ClassNotFoundException, SQLException {
        hoa_don_model = new HoaDonModel();
        jTable1.setModel(hoa_don_model);
        handleSelected();
    }

    private void handleSelected() {
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override

            // ! -> selected 
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    if (!lse.getValueIsAdjusting()) {
                        HoaDonPoJo hoa_don = (HoaDonPoJo) hoa_don_model.getByIndex(jTable1.getSelectedRow());

                        ma_hd_txt.setText(hoa_don.getMaHD());
                        ma_sach_txt.setText(hoa_don.getMaSH());
                        
                        ma_khach_txt.setText(hoa_don.getMaKH());
                        thanh_tien_txt.setText(String.valueOf(hoa_don.getThanhTien()));

                        xoa_btn.setEnabled(true);
                        cap_nhat_btn.setEnabled(true);
                    }
                } catch (Exception e) {
                    System.out.print("hello");
                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });

    }

    private void resetTxtHoaDon() {
        ma_hd_txt.setText(null);
        ma_sach_txt.setText(null);
        ma_khach_txt.setText(null);
        thanh_tien_txt.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ma_hd_txt = new javax.swing.JTextField();
        ma_sach_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ma_khach_txt = new javax.swing.JTextField();
        them_btn = new javax.swing.JButton();
        cap_nhat_btn = new javax.swing.JButton();
        xoa_btn = new javax.swing.JButton();
        init_btn2 = new javax.swing.JButton();
        search_btn2 = new javax.swing.JButton();
        thanh_tien_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "THÔNG TIN HOÁ ĐƠN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("MÃ HOÁ ĐƠN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MÃ SÁCH ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("MÃ KHÁCH");

        them_btn.setText("THÊM");
        them_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btnActionPerformed(evt);
            }
        });

        cap_nhat_btn.setText("CẬP NHẬT");
        cap_nhat_btn.setEnabled(false);
        cap_nhat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap_nhat_btnActionPerformed(evt);
            }
        });

        xoa_btn.setText("XOÁ");
        xoa_btn.setEnabled(false);
        xoa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa_btnActionPerformed(evt);
            }
        });

        init_btn2.setText("LOAD LẠI");
        init_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                init_btn2ActionPerformed(evt);
            }
        });

        search_btn2.setText("TÌM KIẾM");
        search_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btn2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("THÀNH TIỀN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ma_hd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma_khach_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma_sach_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(thanh_tien_txt)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(init_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(them_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cap_nhat_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(xoa_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ma_hd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ma_sach_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ma_khach_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thanh_tien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them_btn)
                    .addComponent(cap_nhat_btn)
                    .addComponent(xoa_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(init_btn2)
                    .addComponent(search_btn2))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void them_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btnActionPerformed
        try {
            // TODO add your handling code here:
            String ma_hoa_don = ma_hd_txt.getText();
            String ma_sach = ma_sach_txt.getText();
            String ma_khach = ma_khach_txt.getText();
            float thanh_tien = Float.parseFloat(thanh_tien_txt.getText());

            HoaDonPoJo hoa_don = new HoaDonPoJo(ma_hoa_don, ma_sach, ma_khach, thanh_tien);
            hoa_don_DAO.addHoaDon(hoa_don);

            hoa_don_model.addElement(hoa_don);
            resetTxtHoaDon();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hơp lệ");
        }
    }//GEN-LAST:event_them_btnActionPerformed

    private void cap_nhat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap_nhat_btnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String maHD = hoa_don_model.getByIndex(jTable1.getSelectedRow()).getMaHD();
            String ma_hoa_don = ma_hd_txt.getText();
            
            String ma_sach = ma_sach_txt.getText();
            String ma_khach = ma_khach_txt.getText();
            
            float thanh_tien = Float.parseFloat(ma_khach_txt.getText());

            int index = jTable1.getSelectedRow();
            HoaDonPoJo hoa_don = hoa_don_model.getByIndex(index);

            HoaDonPoJo hoa_don_update = new HoaDonPoJo(ma_hoa_don, ma_sach, ma_khach, thanh_tien);

            hoa_don_DAO.updateHoaDon(hoa_don_update, maHD);
            initHoaDonTable();
            resetTxtHoaDon();
            cap_nhat_btn.setEnabled(false);
            xoa_btn.setEnabled(false);

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hơp lệ");
        }
    }//GEN-LAST:event_cap_nhat_btnActionPerformed

    private void xoa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa_btnActionPerformed
        try {
            // TODO add your handling code here:
            int index = jTable1.getSelectedRow();
            HoaDonPoJo hoa_don = hoa_don_model.getByIndex(index);

            hoa_don_DAO.removeHoaDon(hoa_don);
            hoa_don_model.removeElement(index);

            cap_nhat_btn.setEnabled(false);
            xoa_btn.setEnabled(false);

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hơp lệ");
        }
    }//GEN-LAST:event_xoa_btnActionPerformed

    private void search_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btn2ActionPerformed
        try {
            // TODO add your handling code here:
            String ma_hoa_don = ma_hd_txt.getText();
            String ma_sach = ma_sach_txt.getText();
            
            String ma_khach = ma_khach_txt.getText();
            float thanh_tien = -1;

            if (!ma_khach_txt.getText().isEmpty()) {
                thanh_tien = Float.parseFloat(ma_khach_txt.getText());
            }

            HoaDonPoJo hoa_don = new HoaDonPoJo(ma_hoa_don, ma_sach, ma_khach, thanh_tien);
            hoa_don_model.getBySearch(hoa_don);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hơp lệ");
        }
    }//GEN-LAST:event_search_btn2ActionPerformed

    private void init_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_init_btn2ActionPerformed
        try {
            initHoaDonTable();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hơp lệ");
        }
    }//GEN-LAST:event_init_btn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cap_nhat_btn;
    private javax.swing.JButton init_btn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ma_hd_txt;
    private javax.swing.JTextField ma_khach_txt;
    private javax.swing.JTextField ma_sach_txt;
    private javax.swing.JButton search_btn2;
    private javax.swing.JTextField thanh_tien_txt;
    private javax.swing.JButton them_btn;
    private javax.swing.JButton xoa_btn;
    // End of variables declaration//GEN-END:variables

}
